; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32 @ 5.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters =
    printable
board_build.partitions = default
build_src_filter = +<*> -<modules/button> -<modules/app> -<modules/command>
build_flags =
    -I src/modules
    -I src/modules/serial_stdio
    -I src/modules/led
    -I src/modules/keypad
    -I src/modules/lcd
    -I src/modules/app
    -I src/modules/utils
    -I src/modules/sound_sensor
    -I src/modules/ds18b20
    -I src/modules/rgb_led
    -I src/modules/button
    -I src/modules/command
    -I src/modules/joystick
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    Wire
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    PaulStoffregen/OneWire@^2.3.8
