; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_speed = 115200
monitor_filters =
    printable
build_src_filter = +<*> -<modules/button> -<modules/app> -<modules/command> -<modules/sound_sensor> -<modules/rgb_led> -<modules/keypad> -<modules/servo> -<modules/signal_conditioner> -<modules/potentiometer> -<modules/ds18b20> -<modules/actuator>
build_flags =
    -I src/modules
    -I src/modules/serial_stdio
    -I src/modules/lcd
    -I src/modules/utils
    -I src/modules/dht11
    -I src/modules/motor
    -I src/modules/joystick
    -I src/modules/led
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    Wire
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
